#!/usr/bin/env bash
# Displays information about subdomains.
# Usage: ./0-world_wide_web <domain> <subdomain>

domain_info() {
    line="$2 $(dig "$2"."$1" +noall +answer | tr '\t' '\n' | tail -2 | tr '\n' ' ')"
    echo "$line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}
# check the number of arguments passed
if [ $# -eq 2 ]; then
    domain_info "$1" "$2"
elif [ $# -eq 1 ]; then
    domain_info "$1" "www"
    domain_info "$1" "lb-01"
    domain_info "$1" "web-01"
    domain_info "$1" "web-02"
fi
