#!/usr/bin/env bash
# Installs and configure Nginx on a remote server

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo nginx -t
sudo nginx -s reload
