#!/usr/bin/env bash
# Installs and configure Nginx on a remote server
# configures a brand new Ubuntu machine

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i "s#server_name _;#server_name _;\n\trewrite ^\/redirect_me https://s3.amazonaws.com/intranet-projects-files/holbertonschool-sysadmin_devops/266/82VsYEC.jpg permanent;#" /etc/nginx/sites-enabled/default

sudo service nginx restart
