#!/usr/bin/env bash
# Perform redirection “301 Moved Permanently”

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

str_to_replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"

sudo sed -i "s#server_name _;#$str_to_replace#" /etc/nginx/sites-enabled/default

sudo service nginx restart
