#!/bin/bash/env bash
# Configure server, Append custom HTTP RESPONSE header
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

str_to_replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/binzam permanent;"

sudo sed -i "s#server_name _;#$str_to_replace#" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

str_to_replace="listen 80 default_server;\\
\\
\\terror_page 404 /404.html;\\
\\tlocation = /404.html {\\
\\t\\troot /var/www/html;\\
\\t\\tinternal;\\
\\t}"

sudo sed -i "s#listen 80 default_server;#$str_to_replace#" /etc/nginx/sites-enabled/default


str_to_replace="listen 80 default_server;\\
\\
\\terror_page 404 /404.html;\\
\\tlocation = /404.html {\\
\\t\\troot /var/www/html;\\
\\t\\tinternal;\\
\\t}"

sudo sed -i "s#listen 80 default_server;#$str_to_replace#" /etc/nginx/sites-enabled/default

sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

sudo nginx -t

sudo service nginx restart
