#!/usr/bin/env bash
# install haproxy

sudo apt-get update
sudo apt-get install -y haproxy
echo "ENABLED=1" | sudo tee /etc/default/haproxy

echo "
backend my_backend
	balance roundrobin
	server 442108-web-01 35.153.98.182:80 check
	server 442108-web-02 54.172.84.26:80 check
" | sudo tee /etc/haproxy/haproxy.cfg

sudo service haproxy start
