#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely,
# Displays I hate the kill command when receiving a SIGTERM signal,
# Displays Y U no love me?! when receiving a SIGINT signal,
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

pid_file="/var/run/myscript.pid"

terminate_script() {
    if [[ -f "$pid_file" ]]; then
        rm "$pid_file"
    fi
    exit
}

sigterm_handler() {
    echo "I hate the kill command"
}

sigint_handler() {
    echo "Y U no love me?!"
}

trap terminate_script SIGQUIT SIGTERM
trap sigterm_handler SIGTERM
trap sigint_handler SIGINT

echo $$ >"$pid_file"

while true; do
    echo "To infinity and beyond"
    sleep 2
done
