#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely with a delay of 2 seconds between each iteration
# Displays "I am invincible!!!" when recieving a SIGTERM signal.

while true; do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I am invincible!!!"' SIGTERM
done
