#!/usr/bin/env bash
# Loops 10 times and prints "Best School" in each iteration
# except, on the 4th iteration, prints bad luck and the 8th iteration print good luck
i=0
while [ $i -lt 10 ]; do
    ((i++))
    if [ $i -eq 4 ]; then
        echo "bad luck"
    elif [ $i -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
done
