#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes
minute=1
hour=0
while [ $hour -lt 13 ]; do
    echo "Hour: $hour"
    while [ $minute -lt 60 ]; do
        echo $minute
        ((minute++))
    done
    ((hour++))
    minute=1
done
